function gen_alert(){
				debugger;
				var val;
				final_list = [];
				lst = ['An Empirical Study of Usages, Updates and Risks of Third-Party Libraries in Java Projects',
 'Improving Cyberbully Detection with User Interaction',
 'MCPA: Program Analysis as Machine Learning',
 'Reliability of Computational Experiments on Virtualised Hardware',
 'Expressing Robot Incapability',
 'About subordinated generalizations of 3 classical models of option pricing',
 'A Polling Model with Reneging at Polling Instants',
 'Effective Extensible Programming: Unleashing Julia on GPUs',
 'Efficient Candidacy Reduction For Frequent Pattern Mining_ final03',
 'Go Wide, Then Narrow: Efficient Training of Deep Thin Networks',
 'Exact Gap between Generalization Error and Uniform Convergence in Random Feature Models',
 'Sensitivity and Generalization in Neural Networks: an Empirical Study',
 'Fuzzy-Klassen Model for Development Disparities Analysis based on Gross Regional Domestic Product Sector of a Region',
 'Some neighborhood-related fuzzy covering-based rough set models and their applications for decision making',
 ' Sliced Multi-Marginal Optimal Transport',
 'Machine Learning-Based Adaptive Receive Filtering: Proof-of-Concept on an SDR Platform',
 'OTIMIZAÇÃO DE REDES NEURAIS USANDO GSO COOPERATIVOS COM DECAIMENTO DE PESOS',
 'tetrys_vs_raw_plr.eps',
 'CP_Artificial Ear_12',
 'QARC: Video Quality Aware Rate Control for Real-Time Video Streaming based on Deep Reinforcement Learning',
 'Neural Variational Gradient Descent',
 'PRICURE: Privacy-Preserving Collaborative Inference in a Multi-Party Setting',
 '../../../publicacoes/comNetSiCloud15/lossRedundantPath_expDemand240_alpha_5_totalNrServers.eps',
 'A template for the arxiv style',
 'IEEE Paper Template in A4 (V1)',
 'GLOBAL STABILIZATION BY MEANS OF',
 'Formal Analysis of the Biological Circuits using Higher-order-logic Theorem Proving',
 'An Executable Structural Operational  Formal Semantics for Python',
 'WAccess - A Web Accessibility Tool based on the latest WCAG 2.2 guidelines',
 'Hedonic Games and Treewidth Revisited',
 'Understand Dynamic Regret with Switching Cost for Online Decision Making',
 'Greedy and Local Ratio Algorithms in the MapReduce Model',
 'Paper Title (use style: paper title)',
 'clem.nbs_freq_round.eps',
 'A Compiler Infrastructure for Accelerator Generators ',
 'Towards Interpretable Authorship Verification',
 'Similar Cases Recommendation using Legal Knowledge Graphs',
 'Development of Word Embeddings for Uzbek Language',
 'Paper Title (use style: paper title)',
 '[UPDATED] Thinking Wave Paper - Exploration of increasing driver’s trust',
 'Computation of Transfer Function with Symbolic Variables ',
 'Approximations for modeling light scattering by spheres with uncertainty in physical parameters',
 'Segmentation of ultrasound images of thyroid nodule for assisting fine needle aspiration cytology',
 'AAAI Proceedings Template',
 'Attention-Informed Mixed-Language Training for Zero-shot Cross-lingual Task-oriented Dialogue Systems',
 'manuscript_antifragility_final_hk',
 'MultiFair: Multi-Group Fairness in Machine Learning',
 'Weighted Tensor Completion for Time-Series Causal Inference',
 "Response to ``Comment on `Origin of the Curie–von Schweidler law and the fractional capacitor from time-varying capacitance [J. Pow. Sources 532 (2022) 231309]' ''",
 'Pheno-Mapper: An Interactive Toolbox for the Visual Exploration of Phenomics Data',
 'N_Peakfound.eps',
 'Discriminative Features via Generalized Eigenvectors',
 'Structural properties of the set of nonrealizable densities',
 'An Inverse Procedural Modeling Pipeline for SVBRDF Maps',
 'Quantum machine learning with adaptive linear optics',
 'Learning and Querying Fast Generative Models for Reinforcement Learning',
 'Type of the Paper (Article',
 'SP-GAN: Sphere-Guided 3D Shape Generation and Manipulation',
 'Date of publication xxxx 00, 0000, date of current version xxxx 00, 0000',
 'Preference-based Multiobjective Virtual Machine Placement: A Ceteris Paribus Approach',
 'query_time_social.eps',
 'Siamese Meta-Learning and Algorithm Selection with ‘Algorithm-Performance Personas’ [Proposal]',
 'Playing Safe, Ten Years Later',
 '%',
 'Truncated Log-concave Sampling with Reflective Hamiltonian Monte Carlo',
 'Topological Inference of Manifolds with Boundary',
 'Interpolation of Dense and Sparse Rational Functions and other Improvements in FireFly',
 'Risk-Averse Optimization for Resilience Enhancement of Complex Engineering Systems under Uncertainties',
 'The most controversial topics in Wikipedia:',
 'super-reflective.pages',
 "Reliving the Dataset: Combining the Visualization of Road Users' Interactions with Scenario Reconstruction in Virtual Reality",
 'Scalable Community Detection over Geo-Social Network',
 'Precise Dataflow Analysis of Event-Driven Applications',
 'Project 412Connect: Bridging Students and Communities',
 'Shifted Lanczos method for quadratic forms with Hermitian matrix resolvents',
 'title',
 'Multi-Transformer: A New Neural Network-Based Architecture for Forecasting S&P Volatility',
 'Linking Stakeholder Viewpoint Concerns with Microservices ',
 'Survey on Cryptocurrency Networking: Context, State-of-the-Art, Challenges',
 'Policy Gradients Beyond Expectations: Conditional Value-at-Risk',
 'Straight to the Gradient:  Learning to Use Novel Tokens for Neural Text Generation',
 'Electronic format submission for AP2000',
 'Font Acknowledgment and Character Extraction of Digital and Scanned Images',
 'Finding Ethereum Smart Contracts Security Issues  by Comparing History Versions',
 'APPLICAZIONE DEL MODELLO NUMERICO “MODFLOW” ALLO STUDIO DI UN ACQUIFERO COSTIERO DELLA PIANURA PONTINA',
 'GCExplainer: Human-in-the-Loop Concept-based Explanations for Graph Neural Networks',
 '116.docx',
 'An Empirical Study of Rule-Based and Learning-Based Approaches for Static Application Security Testing',
 'Information Geometry Approach to Parameter Estimation in Markov Chains',
 'Semantic Robustness of Models of Source Code',
 'Q-learning algorithm for resource allocation in WDMA-based optical wireless communication networks Final2 JE v4 clean',
 'Improving the Tightness of Convex Relaxation Bounds  for Training Certifiably Robust Classifiers',
 'Automated Search Bias Models & YouTube Gender Bias Analysis',
 'On Computing the Hamiltonian Index of Graphs',
 'A study of defect-based error estimates for the Krylov approximation of phi-functions',
 'AutoInt: Automatic Feature Interaction Learning via Self-Attentive Neural Networks',
 'Loop estimator for discounted values in Markov reward processes',
 'A Review of Product Safety Regulations in the European Union',
 'On Worst-case Regret of Linear Thompson Sampling',
 'Learning to Ignore: A Case Study of Organization-Wide Bulk Email Effectiveness',
 'Robustness and Generalization for Metric Learning',
 'AWEU-Net: An Attention-Aware Weight Excitation U-Net for Lung Nodule Segmentation',
 ' Indeterminacy in Latent Variable Models: Characterization and Strong Identifiability',
 'Octopus: A Framework for Cost-Quality-Time Optimization in Crowdsourcing',
 'Efficient Iterative Amortized Inference for Learning Symmetric and Disentangled Multi-Object Representations',
 'Learning Task Agnostic Skills with Data-driven Guidance',
 'Continual Reinforcement Learning deployed in Real-life using Policy Distillation and Sim2Real Transfer',
 'SETIT2003Mahdia1',
 'Display to Labelled Proofs and Back Again for Tense Logics',
 'A Human-Grounded Evaluation Benchmark for Local Explanations of Machine Learning',
 'KQGC: Knowledge Graph Embedding with Smoothing Effects of Graph Convolutions for Recommendation',
 'ncp-WS-2012-casc.eps',
 'sv-lncs',
 'Efficient Non-uniform Quantizer for Quantized Neural Network Targeting Re-configurable Hardware',
 'Data Structure Primitives on Persistent Memory: An Evaluation',
 'Multiplayer Support for the Arcade Learning Environment',
 'Gain More for Less: The Surprising Benefits of  QoS Management in Constrained NDN Networks',
 'A combined entropy and utility based generative model for large scale multiple discrete-continuous travel behaviour data',
 'Decidability of cutpoint isolation for letter-monotonic probabilistic finite automata',
 'Privacy is What We Care About: Experimental Investigation of Federated Learning on Edge Devices',
 'Counting Answer Sets via Dynamic Programming Author=Johannes Fichte, Markus Hecher, Michael Morak, Stefan Woltran',
 'Algorithms and software for projections onto intersections of convex and non-convex sets with applications to inverse problems.',
 'Towards Facilitating Empathic Conversations in Online Mental Health Support: A Reinforcement Learning Approach',
 'Towards a Higher-Order Mathematical Operational Semantics',
 'Ongoing Events in Wikipedia: A Cross-lingual Case Study',
 'TzK: Flow-Based Conditional Generative Model',
 'UE4Sim: A Photo-Realistic Simulator for Computer Vision Applications',
 ' ',
 'DeepThin: A Self-Compressing Library for Deep Neural Networks',
 'Paper Title (use style: paper title)',
 'M3I: Framework for Context-Based Mobile Multimodal Interaction',
 'Paper Title (use style: paper title)',
 'A Survey on Large Scale Metadata Server for Big Data Storage',
 'Alternating Set Quantifiers in Modal Logic',
 'Neural Vector Spaces for Unsupervised Information Retrieval',
 'ED2: Two-stage Active Learning for Error Detection - Technical Report',
 'Trading off Complexity for Expressiveness in Programming Languages: Visions and Preliminary Experiences pdfsubject=Software engineering',
 'IPIC 2021: Paper Protocol Transformation  (final)',
 'A template for the arxiv style',
 'Automatically Composing Representation Transformations  as a Means for Generalization',
 'At the Interface  of Algebra and Statistics',
 'Understanding the (In)Effectiveness of Content Moderation: A Case Study of Facebook in the Context of the U.S. Capitol Riot',
 'A study on the Interpretability of Neural Retrieval Models using DeepSHAP',
 'Finding Points in Convex Position in Density-Restricted Sets',
 'Paper Title (use style: paper title)',
 'Fundamental Limits of Combinatorial Multi-Access Caching',
 'Addressing the Privacy Implications of Mixed Reality: A Regulatory Approach',
 'Bio-Ontologies Submission Template',
 "Understanding parents' perceptions of children's cybersecurity awareness in Norway",
 'Secure Zones: an Attribute-Based Encryption Advisory System for Safe Firearms',
 'Word Template',
 'Integrated Sensing and Earthmoving Vehicle for Lunar Landing Pad Construction',
 'Paper Title (use style: paper title)',
 'Every Frame Counts: Joint Learning of Video Segmentation and Optical Flow',
 'SOP-BCZ99-time.eps',
 'On the Double Descent of Random Features Models Trained with SGD',
 'Uncertainty-based Traffic Accident Anticipation with Spatio-Temporal Relational Learning',
 'mQAPViz: A divide-and-conquer multi-objective optimization algorithm to compute large data visualizations',
 'Reliable Algorithm for Extracting Web Data ',
 'TrojanNet: Embedding Hidden Trojan Horse Models in Neural Networks',
 'Material Recognition for Automated Progress Monitoring using Deep Learning Methods',
 'TransProteus Final For Arxive',
 'Author Guidelines',
 'Global Optimality Beyond Two Layers: Training Deep ReLU Networks via Convex Programs',
 'ICIS 2007 Proceedings Template',
 'A 8 bits Pipeline Analog to Digital Converter Design for High S',
 'A mechanism-based gradient damage model for metallic fracture',
 'MultiScope: Efficient Video Pre-processing for  Exploratory Video Analytics',
 'Overleaf Example',
 'Long-term electricity market agent based model validation using genetic algorithm based optimization',
 'Under Lock and Key:  A Proof System for a Multimodal Logic',
 'Flow-Aware Platoon Formation of Connected Automated Vehicles in a Mixed Traffic with Human-driven Vehicles',
 'Stabilizing Equilibrium Models by Jacobian Regularization',
 'Smooth q-Gram, and Its Applications to Detection of Overlaps among Long, Error-Prone Sequencing Reads',
 'Flatter is better: Percentile Transformations for Recommender Systems',
 'Fairness, Integrity, and Privacy in a Scalable Blockchain-based Federated Learning System',
 'SideRand',
 'Parallel cut-cell algorithm for free-boundary Grad-Shafranov',
 'Structure-from-Motion using Dense CNN Features with Keypoint Relocalization',
 'Estimating Stochastic Linear Combination of Non-linear  Regressions Efficiently and Scalably',
 'The Hierarchical Chinese Postman Problem: the slightest disorder makes it hard,  yet disconnectedness is manageable',
 'Open Access proceedings Journal of Physics: Conference series',
 '_',
 'LawBreaker: An Approach for Specifying Traffic Laws and Fuzzing Autonomous Vehicles',
 'A Hybrid Approach to Domain-Specific Entity Linking',
 'Gourds: a sliding-block puzzle with turning',
 'SMoTherSpectre: exploiting speculative execution through port contention',
 'Competing Bandits:  The Perils of Exploration under Competition',
 'Proceedings Template - WORD',
 'Termite-hill, from natural to artificial termites in sensor networks',
 'A linear streaming algorithm for community detection in very large networks',
 'nongreedy_reveal_vary_gamma_D.eps',
 'Classification via an Embedded Approach',
 'C:\\PII266\\marcos\\congres\\eusipco92\\eusipco92.wpd',
 'Paper Title (use style: paper title)',
 'A Hybrid Model for Forecasting Short-Term Electricity Demand',
 'Semantic Photo Manipulation with a Generative Image Prior',
 'A Deep Framework for Cross-Domain and Cross-System Recommendations',
 '10pt',
 'batch.eps',
 'Few-shot link prediction via graph neural networks for Covid-19 drug-repurposing',
 'sty_ga.eps',
 'NwTheta7CellAlpha001Begin9010EndLocalLRI.eps',
 'Article',
 'A Review of Financial Accounting Fraud Detection based on Data Mining Techniques',
 'Algorithm based on BDD',
 'A Preliminary Study for a Quantum-like Robot Perception Model',
 'Cleaning Denial Constraint Violations through Relaxation',
 'A Predictive Model using the Markov Property',
 'A Survey on Hardware-based Security Mechanisms for Internet of Things',
 'AAAI Proceedings Template',
 'Optimal epidemic dissemination',
 '20200722 - Social Media and Health Misinformation during the US COVID Crisis',
 'Multi-Access Distributed Computing',
 'CloudTests_IM2013_camera_ready_v3.fm',
 'Open Access proceedings Journal of Physics: Conference series',
 'How Biased is the Population of Facebook Users? Comparing the Demographics of Facebook Users with Census Data to Generate Correction Factors',
 'Improved Load Balancing in Large Scale Systems using Attained Service Time Reporting',
 'How to Train Deep Variational Autoencoders and Probabilistic Ladder Networks',
 'A Comprehensive Safety Engineering Approach for Software-Intensive Systems Based on STPA',
 'The Non-uniform Fast Fourier Transform in Computed Tomography (Pre-dissertation Report)',
 'KompaRe: A Knowledge Graph Comparative Reasoning System',
 'An investigation of MMM Ponzi scheme on Bitcoin',
 'A hierarchical preconditioner for wave problems in quasilinear complexity',
 'Digraphs with Distinguishable Dynamics',
 'Evaluating Deep Neural Networks for Image Document Enhancement',
 'DNA Solution of the Maximal Independent Set Problem',
 'Paper Title (use style: paper title)',
 'Mesh Reconstruction from Aerial Images for Outdoor Terrain Mapping Using Joint 2D-3D Learning',
 'Normalized Wasserstein Distance for Mixture Distributions with Applications in Adversarial Learning and Domain Adaptation ',
 'Using a Binary Classification Model to Predict the Likelihood of Enrolment to the Undergraduate Program of a Philippine University',
 'Differentiating through the Fréchet Mean',
 'ProphetNet: Predicting Future N-gram for Sequence-to-Sequence Pre-training',
 'Personalized Federated Learning with Clustered Generalization',
 'Reliability.eps',
 'Handgun detection using combined human pose and weapon appearance',
 'LoMEF: A Framework to Produce Local Explanations for Global Model Time Series Forecasts',
 'Learning How to Walk: Warm-starting Optimal Control Solverwith Memory of Motion',
 'Extending Expressive Access Policies with Privacy Features',
 'Model-Based Development of Distributed Embedded Systems by the Example of the Scicos/SynDEx Framework',
 'A Flexible Proof Format for SAT Solver-Elaborator Communication',
 'Multimodal Feature Fusion for Video Advertisements Tagging Via Stacking Ensemble',
 'Accuracy, Interpretability, and Differential Privacy via Explainable Boosting',
 'SOS Decomposition',
 'Identity-Aware CycleGAN for Face Photo-Sketch Synthesis and Recognition',
 'Tracking a Threshold Crossing Time of a Gaussian Random Walk Through Correlated Observations ',
 'Assessing Impact of Data Partitioning forApproximate Memory in C/C++ Code',
 'ReportV2',
 'Generalized Hidden Parameter MDPs Transferable Model-based RL in a Handful of Trials',
 'CIB 2011-W78-W102-Paper Example',
 'Catastrophic forgetting: still a problem for DNNs',
 'On Construction of a Class of Orthogonal Arrays',
 'HoloScope: Topology-and-Spike Aware Fraud Detection',
 'A Case Study on Pros and Cons of Regular Expression Detection and Dependency Parsing for  Negation Extraction from German Medical Documents. Technical Report',
 'Learned Low Precision Graph Neural Networks',
 'Efficient Implementation of Non-linear Flow Law Using Neural Network into the Abaqus Explicit FEM code',
 'Human-agent coordination in a group formation game',
 'Open-Retrieval Conversational Question Answering',
 'SSLP',
 ' Benchmarking, Analysis, and Optimization of Serverless Function Snapshots ',
 'Use of IF for assessing individual articles',
 'Automatic Comic Generation with Stylistic Multi-page Layouts and Emotion-driven Text Balloon Generation',
 'NullaNet: Training Deep Neural Networks for Reduced-Memory-Access Inference',
 'Rational Krylov methods for fractional diffusion problems on graphs',
 'Optimal Scheduling for Fair Resource Allocation in Ad Hoc Networks with Elastic and Inelastic Traffic',
 'Multi-source Distilling Domain Adaptation',
 'Paper Title (use style: paper title)',
 'Paper Title (use style: paper title)',
 'A review of machine learning in processing remote sensing data for mineral exploration',
 'Understanding Concurrency Vulnerabilities in Linux Kernel',
 'SENSOR-BASED SPREADER AUTOMATION FOR REDUCING SALT USE AND IMPROVING SAFETY',
 'Community-Empowered Air Quality Monitoring System',
 'Enhanced Performance for the encrypted Webthrough TLS Resumption across Hostnames',
 'Byzantine Lattice Agreement in Asynchronous Systems',
 'Issues in Object Detection in Videos using Common Single-Image CNNs',
 'Nigam-Pollock article',
 'An Improved Algorithm for hypot(a,b)',
 'Total irregularity of a graph',
 'Gillian: Compositional Symbolic Execution for All',
 'Optimistic Proximal Policy Optimization',
 'iphone teacher arxiv',
 'Capsule Graph Neural Networks with EM Routing',
 'Komputerowe algorytmy ekstrakcji i śledzenia obiektów w czasie rzeczywistym',
 'Performance Impact of Idle Mode Capability on Dense Small Cell Networks with  LoS and NLoS Transmissions',
 'cost-vs-nepochs-netflix.eps',
 'Adversarial Machine Learning in Recommender Systems: State of the art and Challenges',
 'Delay-Constrained Rate Control for Real-Time Video Streaming with Bounded Neural Network',
 'Situating Recommender Systems in Practice: Towards Inductive Learning and Incremental Updates',
 'A template for the arxiv style',
 'On the Convergence of Decentralized Gradient Descent',
 'Untitled',
 'LieTransformer: Equivariant self-attention for Lie Groups',
 'Reconfigurable Inverted Index',
 'Stochastic Discontinuous Galerkin Methods with Low–Rank Solvers for Convection Diffusion Equations',
 'BERN2_20220106_for_arxiv',
 'Fast and Scalable Inference of Multi-Sample Cancer Lineages',
 ' Integrating State of the Art Compute, Communication, and Autotuning Strategies to Multiply the Performance of the Application Programm CPMD for Ab Initio Molecular Dynamics Simulations ',
 'Tiny Buffer TCP for Data Center Networks',
 'Contraction-Based Sparsification in Near-Linear Time',
 'Structural Consensus in Networks with Directed Topologies and Its Cryptographic Implementation',
 'Chapter_Michel-Lavoue_2011',
 'Paper Title (use style: paper title)',
 'Deep Neural Network-based Enhancement for Image and Video Streaming Systems: A Survey and Future Directions',
 'Self-calibration of a differential wheeled robot using only a gyroscope and a distance sensor',
 'tase-submitted.pdf',
 'Improved Onlooker Bee Phase in Artificial Bee Colony Algorithm',
 'Learning Sampling in Financial Statement Audits using Vector Quantised Autoencoder Neural Networks',
 'arxiv',
 'ChASE - A Distributed Hybrid CPU-GPU Eigensolver for Large-scale Hermitian Eigenvalue Problems',
 'AnICA: Analyzing Inconsistencies in Microarchitectural Code Analyzers',
 'Ensemble deep learning: A review',
 'NOH-NMS: Improving Pedestrian Detection by Nearby Objects Hallucination',
 'Adversarial Knowledge Transfer from Unlabeled Data',
 'Personalized Federated Deep Learning for Pain Estimation From Face Images',
 'Total nitrogen estimation in agricultural soils via aerial multispectral imaging and LIBS',
 'Towards Interpretable and Learnable Risk Analysis for Entity Resolution',
 'Generalized Hindsight for Reinforcement Learning',
 'In-situ Stochastic Training of MTJ Crossbar based Neural Networks',
 'Measuring the Cost Effectiveness of Stress Test Orders for Distributed Real-Time Systems based on Fault Criticalities',
 'Sharp Waiting-Time Bounds for Multiserver Jobs',
 ' Cryptographically Secure Information Flow Control on Key-Value Stores',
 'Actor-based Risk Analysis for Blockchains in Smart Mobility',
 'Getting More Out Of Syntax with PropS',
 'Ontology Focusing: Knowledge-enriched Databases on Demand',
 'A Dataset and Application for Facial Recognition of Individual Gorillas in Zoo Environments',
 'Learning to Learn Image Classifiers with Informative Visual Analogy',
 'Regularized Q-learning',
 'Biased Weak Polyform Achievement Games',
 'GLOBAL STABILIZATION BY MEANS OF',
 '附表5：',
 'The Title of the Paper: Perhaps a Very Long Title, or an Extremely Long, Title that Spans More Than One Line',
 's0003a_01.eps',
 'Proceedings Template - WORD',
 'Real World Morphological Evolution is Feasible',
 'IADA: Iterative Adversarial Data Augmentation Using Formal Verification and Expert Guidance',
 'TCOM Submission v2',
 'Combining Deep Learning and Mathematical Morphology for Historical Map Segmentation',
 'Erdos-Pósa property of long holes',
 '../../../results/plots/SantaBarbara_uplow_bound.eps',
 'Neighborhood Troubles: On the Value of User Pre-Filtering To Speed Up and Enhance Recommendations',
 'Machine Learning Students Overfit to Overfitting',
 'Unsupervised Object-Based Transition Models for 3D Partially Observable Environments',
 'Recognition of Indian Sign Language in Live Video',
 'Well-quasi-ordering H-contraction-free graphs',
 'Paper Title (use style: paper title)',
 'Stanisław KOWALSKI1, Jan MALINOWSKI2',
 '未命名',
 'DCN-M: Improved Deep & Cross Network for  Feature Cross Learning in Web-scale Learning to Rank Systems',
 'Comp Power vs KeyLenght CoNaIISI 2018  w-autor v1',
 'varyIR.eps',
 'Effective Interfaces for Student-Driven Revision Sessions for Argumentative Writing',
 'Pros and Cons of GAN Evaluation Measures: New Developments',
 'Paper Title (use style: paper title)',
 'tkde-2740932-pp.pdf',
 ' Dual Skipping Guidance for Document Retrieval with Learned Sparse Representations',
 "Using Prior Knowledge to Guide BERT's Attention in Semantic Textual Matching Tasks",
 'time_evolution.eps',
 'A Unified Framework for Marketing Budget Allocation',
 'P4CEP: Towards In-Network Complex Event Processing',
 'eh_multi_relay_v9.dvi',
 'Performance Limits of Single-Anchor mm-Wave Positioning',
 'Between Subjectivity and Imposition: Power Dynamics in Data Annotation for Computer Vision',
 'Paper Title (use style: paper title)',
 'max-clique-finalb.dvi',
 'Prisons',
 'When Good Components Go Bad: Formally Secure Compilation Despite Dynamic Compromise',
 "Sensitivity analysis for 3D Maxwell's equations and its use in the resolution of an inverse medium problem at fixed frequency",
 'Privacy-Aware Recommendation with Private-Attribute Protection using Adversarial Learning',
 'Multiple Instance Learning for Detecting Anomalies over Sequential Real-World Datasets',
 'Context-Aware Service Utilisation in the Clouds and Energy Conservation',
 'Value Iteration Networks',
 'Renyi',
 'GIANT: Scalable Creation of a Web-scale Ontology',
 'IEEE GRSM',
 'typeinst_v9',
 'Sensing the Breath: A Multimodal Singing Tutoring Interface with Breath Guidance',
 'A heuristic approach to author name disambiguation in bibliometrics',
 'Relevance Classification of Flood-related Twitter Posts via Multiple Transformers',
 'Conformance checking: A state-of-the-art literature review',
 'Enhanced Fairness Testing via Generating Effective Initial  Individual Discriminatory Instances',
 'Learning Non-Lambertian Object Intrinsics across ShapeNet Categories',
 'Approximate synchronization of coupled multi-valued logical networks',
 'Article',
 'Fast and flexible preconditioners for solving multilinear systems',
 'Format guide for AIRCC',
 'A new upper bound for spherical codes',
 'AAAI Proceedings Template',
 'INSTRUÇÕES PARA A PREPARAÇÃO E SUBMISSÃO DE TRABALHOS PARA O XLI CONGRESSO BRASILEIRO DE EDUCAÇÃO EM ENGENHARIA',
 'SIGCHI Conference Paper Format',
 'baller2vec: A Multi-Entity Transformer ForMulti-Agent Spatiotemporal Modeling',
 'Discretization and digitization schemes based on LCL  collections of cells in N dimensions',
 'K:\\pooling\\Critical\\Documentation\\Accepted and Puplished Papers\\For Archiving',
 'Tuning Recurrent Neural Networks with Reinforcement Learning',
 'CaseXPert A Process Planning System with Feature Based Neural Network Search Strategy for Aluminum Extrusion Die Manufacturing',
 'Value Iteration in Continuous Actions, States and Time',
 'Multi-task Maximum Entropy Inverse Reinforcement Learning',
 ', Vol1. No.1, JIC, Journal of Informaiton and Computing Science',
 'Parallel Bayesian Optimization of Multiple Noisy Objectiveswith Expected Hypervolume Improvement',
 'Assessing Algorithmic Biases for Musical Version Identification',
 'The Title of the Paper Goes Here, in Title Case and Title Style',
 'Paper Title (use style: paper title)',
 'Modeling Continuous Stochastic Processes with Dynamic Normalizing Flows',
 'Land Eligibility for Renewabe Energy Systems',
 'DynO: Dynamic Onloading of Deep Neural Networks from Cloud to Device',
 '(mcdermott03a.pdf)',
 'Automated detection and classification of cryptographic algorithms in binary programs through machine learning',
 'On Arbitrary Dimension Hermitian Hull linear codes from Hermitian self-orthogonal codes and New Hermitian Self-Orthogonal GRS Codes',
 'A Unified Framework for Analyzing and Detecting Malicious Examples of DNN Models',
 'Sharp Analysis of Smoothed Bellman Error Embedding',
 'Socket Intents: OS Support for Using Multiple Access Networks and its Benefits for Web Browsing',
 'Proceedings Template - WORD',
 'A parallel Fortran framework for neural networks and deep learning',
 'Randomized Cholesky Factorization',
 '/home/frevo/srrg_papers/2019_paper_grisetti_solver/plots/plgo_multisolvers_lm_100_nokern_term//timing_plots_span/histogram_cum_time_multitrials_kitti_00_landmarks_high_span.eps',
 'Predictive Inequity in Object Detection',
 'Comparing Different Deep Learning Architectures for Classification of Chest Radiographs',
 'Structural Deep Clustering Network',
 'Iconify: Converting Photographs into Icons',
 '10-Page-ICCSEA2012-Web-page Prediction for Domain Specific Web-search using Boolean Bit Mask',
 'SELECTIVE PRIVACY IN IOT SMART-FARMS FOR BATTERY-POWERED DEVICE LONGEVITY',
 'Cyclic Arbitrage in Decentralized Exchange Markets',
 'courbe_turbo_codes.eps',
 'Profiling presence patterns and segmenting user locations from cell phone data',
 'The logic of contextuality',
 'Subgraph Matching Kernels for Attributed Graphs',
 'Uncertainty Bounds for Multivariate Machine Learning Predictions on High-Strain Brittle Fracture',
 "Robot Rights? Let's Talk about Human Welfare Instead",
 'OntologyEDA_V2 2a',
 'INSTRUCTIONS TO AUTHORS FOR THE PREPARATION OF MANUSCRIPTS',
 'Optimization of the Sparse Multi-Threaded Cholesky Factorization for A64FX',
 'Paper Title (use style: paper title)',
 'Pushdown Automata and Context-Free Grammars in Bisimulation Semantics',
 'Exploratory Data Analysis of Urdu Poetry',
 'Proceedings Template - WORD',
 'Learning Task Relatedness in Multi-Task Learning for Images in Context',
 'Modular population protocols',
 'Assessing Semantic Quality of Web Directories Structure',
 'When the Differences in Frequency Domain are Compensated: Understanding and Defeating Modulated Replay Attacks on Automatic Speech Recognition',
 'Research Doc : NFT Platforms - Vulnerabilities and Security Risks',
 'Computing the Newton-step faster than Hessian accumulation',
 ' pdfauthor=P. Öffner',
 'PyArmadillo: a streamlined linear algebra library for Python',
 'A Cubical Language for Bishop Sets',
 'ShapeFlow: Dynamic Shape Interpreter for TensorFlow',
 'Paper Title (use style: paper title)',
 'Generalized Approximate Survey Propagation  for High-Dimensional Estimation',
 'Optimization Theory for ReLU Neural Networks Trained with Normalization Layers',
 'Virtual Reality Sickness Mitigation Methods: A Comparative Study in a Racing Game',
 'Defect Diagnosis in Rotors Systems by Vibrations Data Collectors Using Trending Software',
 'Convolutional Neural Networks on Graphs with Chebyshev Approximation, Revisited',
 'Interpretable Aesthetic Analysis Model for Intelligent Photography Guidance Systems',
 'Prodromal Diagnosis of Lewy Body Diseases Based on the Assessment of Graphomotor and Handwriting Difficulties',
 'Your Title',
 'Multilevel Gibbs Sampling for Bayesian regression',
 'Kambhampati00.dvi',
 'Maximum Coverage in the Data Stream Model: Parameterized and Generalized',
 'Transaction / Regular Paper Title',
 'Analytical Differential Calculus with Integration',
 'Convex Relaxation Methods for Community Detection',
 'Learning to Rank Rationales for Explainable Recommendation',
 'kaddah16_revised',
 'Dagstuhl12442_AZ',
 'A Case Study in Engineering a Conversational Programming Assistant’s Persona',
 'Receptive Field Analysis of Temporal Convolutional Networks for Monaural Speech Dereverberation',
 'Study on Transfer Learning Capabilities for Pneumonia Classification in Chest-X-Rays Images',
 'Studying Person-Specific Pointing and Gaze Behavior for Multimodal Referencing of Outside Objects from a Moving Vehicle',
 'Two-Manifold Problems with Applications to Nonlinear System Identification',
 'EQR104_comp.ps',
 'Probing a Set of Trajectories to Maximize Captured Information',
 'The CaLiGraph Ontology as a Challenge for OWL\\protect \\unhbox \\voidb@x \\protect \\penalty \\@M  {}Reasoners',
 'CHI_2016_SUR',
 'Learning to Select Cuts for Efficient Mixed-Integer Programming',
 'Transition Watchpoints: Teaching Old Debuggers New Tricks',
 '2019 Formatting Instructions for Authors Using LaTeX',
 'The Design and Implementation of Typed Scheme',
 'Untitled',
 'Serverless Workflows with Durable Functions and Netherite',
 'Format guide for AIRCC',
 'Loss-Aversively Fair Classification',
 'Maximizing information from chemical engineering data sets: Applications to machine learning',
 'Coalgebraic Trace Semantics for Continuous Probabilistic Transition Systems',
 'Analysis of the Performance of Algorithm Configurators for Search Heuristics with Global Mutation Operators',
 'TMRNetwork',
 'sv-lncs',
 'a.eps',
 'Title of the Paper○',
 'Paper Title (use style: paper title)',
 'Implementing G-Machine in HyperLMNtal',
 'Taming Uncertainty in the Assurance Process of Self-Adaptive Systems: a Goal-Oriented Approach',
 'Query Expansion for Cross-Language Question Re-Ranking',
 'eCommerceGAN : A Generative Adversarial Network for E-commerce',
 'On-line Learning with Abstention',
 'On Fair Division with Binary Valuations Respecting Social Networks',
 'Neural Melody Composition from Lyrics',
 'SoK: Opportunities for Software-Hardware-Security Codesign for Next Generation Secure Computing',
 'The Variational Predictive Natural Gradient',
 'courbe10.eps',
 "What's in Score for Website Users: A Data-driven Long-term Study on Risk-based Authentication Characteristics (Pre-proceedings Version)",
 'Quantized VCG Mechanisms for Polymatroid Environments ',
 'CARL: Controllable Agent with Reinforcement Learning for Quadruped Locomotion',
 'IJME',
 'Selection Bias-Corrected Visualization via Dynamic Reweighting',
 'TT-Rec: Tensor Train Compression  for Deep Learning Recommendation Model Embeddings',
 'Application of Artificial Neural Networks in Predicting Abrasion Resistance of Solution Polymerized Styrene-Butadiene Rubber Based Composites',
 "A Study on the Open Source Digital Library Software's: Special Reference to DSpace, EPrints and Greenstone",
 'push_conflicts.eps',
 'Author Guidelines for 8',
 'Learning Illumination from Diverse Portraits',
 'Blah Blah Blah',
 'Multi-VFL: A Vertical Federated Learning System for Multiple Data and Label Owners',
 'Detecting Road Obstacles by Erasing Them',
 'The GDPR Enforcement Fines at Glance',
 'Online Meta-Learning',
 'ISA_02_2010',
 'Sampling-based 3-D Line-of-Sight PWA Model Predictive Control for Autonomous Rendezvous and Docking with a Tumbling Target',
 'TransRefer3D: Entity-and-Relation Aware Transformer  for Fine-Grained 3D Visual Grounding',
 'Relative Importance Sampling For Off-Policy Actor-Critic  in Deep Reinforcement Learning',
 'Agree to Disagree: Subjective Fairness in Privacy-Restricted Decentralised Conflict Resolution',
 'HTRU2-compare-f1-update.eps',
 'Graph-based Deep Learning for Communication Networks: A Survey',
 'Efficent Edge Detection on Low-Cost FPGAs',
 'Large-Scale Learnable Graph Convolutional Networks',
 ' Differential Dynamic Programming Neural Optimizer ',
 'Format guide for AIRCC',
 'Locally Solvable Tasks  and the Limitations of Valency Arguments',
 'Towards Retina-Quality VR Video Streaming: 15ms Could Save You 80% of Your Bandwidth',
 'A Modular Approach to Block-diagonal Hessian Approximationsfor Second-order Optimization Methods',
 'Toward Performance-Portable PETSc for GPU-based Exascale Systems',
 'Symbolic Music Generation with Diffusion Models',
 'Self-Organizing Teams in Online Work Settings',
 'Fully Convolutional Neural Networks for Raw Eye Tracking Data Segmentation, Generation, and Reconstruction',
 'UI-Net: Interactive Artificial Neural Networks',
 'Image Matters: Detecting Offensive and Non-Compliant Content / Logo in Product Images',
 'Preparation of Papers in Two-Column Format for the Proceedings of the 2004 Sarnoff Symposium',
 'Metaverse: Survey, Applications, Security, and Opportunities',
 'Fast CUDA-Aware MPI Datatypes without Platform Support',
 'Mining Complex Hydrobiological Data with Galois Lattices',
 'TANH Implementation',
 'Paper Title (use style: paper title)',
 'Cached and Confused: Web Cache Deception in the Wild',
 'A multi-order smoothed particle hydrodynamics method for cardiac electromechanics with the Purkinje network',
 'Fairness in ad auctions through inverse proportionality',
 'Sharpening Your Tools: Updating bulk_extractor for the 2020s.',
 'A Reliable Link-adaptive Position-based Routing Protocol for Flying Ad hoc Network',
 'Hate Raids on Twitch: Echoes of the Past, New Modalities, and Implications for Platform Governance',
 'Optimizing Black-box Metrics with Adaptive Surrogates',
 'Change Actions: Models of Generalised Differentiation',
 'Cuttlefish: Library for Achieving Energy Efficiency in Multicore Parallel Programs',
 'Bypassing Backdoor Detection Algorithms in Deep Learning',
 'An Application of Newsboy Problem in Supply Chain Optimisation of Online Fashion E-Commerce',
 'PythonFOAM: In-situ data analyses with OpenFOAM and Python',
 'Mind Your Solver! On Adversarial Attack and Defense for Combinatorial Optimization',
 'Facial Key Points Localization',
 'Paper Title (use style: paper title)',
 'Paper Title (use style: paper title)',
 'Density-Based Dynamic Curriculum Learning for Intent Detection',
 "``Why is `Chicago' deceptive?'' Towards Building Model-Driven Tutorials for Humans ",
 'step-converge.eps',
 'Fig3_SamplingByCorrelation.eps',
 'Proceedings Template - WORD',
 'СБОРНИК НАУЧНЫХ ТРУДОВ НГТУ, 1995, №1, 109-115',
 'Paper Title (use style: paper title)',
 'MultiGrain: a unified image embedding for classes and instances',
 'Image Quality Enhancement Using Pixel-Wise Gamma Correction',
 'Is Image-to-Image Translation the Panacea for Multimodal Image Registration? A Comparative Study',
 'MIDMod-OSN: A Microscopic-level Information Diffusion Model for Online Social Networks',
 'Tug the Student to Learn Right: Progressive Gradient Correcting by Meta-learner on Corrupted Labels',
 'Metamath Zero: The Cartesian Theorem Prover',
 'DeepTracker: Visualizing the Training Process of Convolutional Neural Networks',
 'Model-Free Approach to Fair Solar PV Curtailment Using Reinforcement Learning',
 'Paper Title (use style: paper title)',
 'Article',
 'Minimum Viable Model Estimates for Machine Learning Projects',
 'XXX',
 'A Node Elimination Algorithm for Cubature of High-Dimensional Polytopes',
 'CAT: Compression-Aware Training for bandwidth reduction',
 'Paper Title (use style: paper title)',
 'Time for a Background Check! Uncovering the impact of Background Features on Deep Neural Networks',
 'R-GSN: The Relation-based  Graph Similar Network for Heterogeneous Graph',
 'CLOUD COMPUTING 2010-camera ready4',
 'A Mobile Computing Architecture for Numerical Simulation',
 'Paper Title (use style: paper title)',
 'Reliable Weakly Supervised Learning: Maximize Gain and Maintain Safeness',
 'CF2_IJCAI_2021-2.pdf',
 'Description',
 'Empirical Study on Detecting Controversy in Social Media',
 'stack-seqalt.tex',
 'Self-supervised Graph-level Representation Learning  with Local and Global Structure',
 'Analysis of HC selection for MCTS in simultaneous move games',
 'Improved VIV response prediction using adaptive parameters and data clustering',
 'A Sensor Fusion-based Cutting Device Attitude Control to Improve the Accuracy of Korean Cabbage Harvesting',
 'A Multisensory Learning Architecture for Rotation-invariant Object Recognition',
 'Towards a Cellular Automata Based Network Intrusion Detection System with Power Level Metric in Wireless Adhoc Networks (IDFADNWCA)',
 'Multichannel End-to-end Speech Recognition ',
 'Proceedings Template - WORD',
 'An Extensive Analytical Approach on Human Resources using Random Forest Algorithm',
 "``Short is the Road that Leads from Fear to Hate'': Fear Speech in Indian WhatsApp Groups",
 'Quality of Uncertainty Quantification for Bayesian Neural Network Inference',
 'A Pairwise Fair and Community-preserving Approach to k-Center Clustering',
 'The p-AAA Algorithm for Parametric Dynamical Systems',
 'ambite01a.dvi',
 'Scalable Spectral Clustering Using Random Binning Features',
 'ECMLG2014_Proceedings-dropbox.pdf',
 'Gender and Collaboration Patterns in a Temporal Scientific Authorship Network',
 'Neural Crossbreed: Neural Based Image Metamorphosis',
 'BIYIHA NLEND Article ENGLISH',
 '第三届“认证杯”数学中国',
 'Runtime Mitigation of Packet Drop Attacks in Fault-tolerant Networks-on-Chip',
 'What Can Heterogeneity Add to the Scientometric Map? Steps towards algorithmic historiography',
 'Manipulation of Stable Matchings using Minimal Blacklists',
 'Bayesian Optimization in a Billion Dimensions  via Random Embeddings',
 'Cascading Bandits',
 'sv-lncs',
 ' Spaceland Embedding of Sparse Stochastic Graphs ',
 'Memoria_v15',
 'Distributional Reinforcement Learning with Quantile Regression',
 'Agile and Pro-Active Public Administration as a Collaborative Networked Organization',
 'GLADAS: Gesture Learning ',
 ' Several classes of 0-APN power functions over F2n',
 'Hierarchical Data Reduction and Learning',
 'plot_scaled.eps',
 'Polynomial time algorithms in invariant theory  for torus actions',
 'Adversarial Random Forest Classifier for Automated Game Design',
 'Elastic Graph Neural Networks',
 'Contact Tracing: Beyond the Apps',
 'When Follow is Just One Click Away: Understanding Twitter Follow Behavior in the 2016 U.S. Presidential Election',
 'Mario Level Generation From Mechanics Using Scene Stitching',
 'Problems of Inheritance at Java inner class-Formatted',
 'Adversarial Machine Learning: Perspectives from Adversarial Risk Analysis',
 'Sid_LBM_2009_oct_19_8 am',
 'Promises and Perils of Inferring Personality on GitHub',
 'Security risk assessment in Internet of Things systems',
 'Pointwise-in-time a posteriori error control for time-fractional parabolic equations',
 'Learning Algebraic Multigrid Using Graph Neural Networks',
 'dMFEA-II: An Adaptive Multifactorial Evolutionary Algorithm for Permutation-based Discrete Optimization Problems',
 ' How to Train your Quadrotor: A Framework for Consistently Smooth and Responsive Flight Control via Reinforcement Learning ',
 'Transaction / Regular Paper Title',
 'Enabling microbiome research on personal devices',
 '20200621001csm.eps',
 'Paper Title (use style: paper title)',
 'A Payload Optimization Method for Federated Recommender Systems',
 'Deriving Static Security Testing from Runtime Security Protection for Web Applications',
 'Dancing Pigs or Externalities? Measuring the Rationality of Security Decisions',
 'Spin-wave dynamics in a hexagonal 2-D magnonic crystal',
 'Static Analysis Deployment Pitfalls',
 'Priprava prispevka za Elektrotehniški vestnik',
 'Domain Adversarial Reinforcement Learning',
 'Modeling Realistic Adversarial Attacks against Network Intrusion Detection Systems',
 'Scalable Training of Inference Networks for Gaussian-Process Models',
 'Would You Ask it that Way? Measuring and Improving Question Naturalness for Knowledge Graph Question Answering',
 'Discovering Hidden Structure in High Dimensional Human  Behavioral Data via Tensor Factorization',
 'comparison.ps',
 'A Machine Learning Imaging Core using Separable FIR-IIR Filters',
 'Escaping Saddles with Stochastic Gradients',
 'SLDs for Visualizing Multicolor Elevation Contour Lines in Geo-Spatial Web Applications',
 'GRMR: Generalized Regret-Minimizing Representatives',
 'A Comparative Study of Programming Languages in Rosetta Code',
 'ICRA_V6',
 'My title',
 'gelmanrubin-all.eps',
 'Validated Objects: Specification, Implementation, and Applications',
 'Topic Discovery through Data Dependent and Random Projections',
 'Cognitive Visual-learning Environment for PostgreSQL.docx',
 'SM-SGE: A Self-Supervised Multi-Scale Skeleton Graph Encoding Framework for Person Re-Identification',
 'Characterization and Classification of Human Body Channel As a Function of Excitation and Termination Modalities',
 'Original file was jvis_final.tex',
 'Stochastic Shortest Paths and Weight-Bounded Properties in Markov Decision Processes',
 'A tier-based typed programming language characterizing Feasible Functionals',
 'Paper Title (use style: paper title)',
 '%',
 'Practical Algorithms for STV and Ranked Pairs with Parallel Universes Tiebreaking',
 'Consistent Non-Parametric Methods for Adaptive Robustness',
 'Joint Optimization of AI Fairness and Utility: A Human-Centered Approach',
 'Improbotics: Exploring the Imitation Game using Machine Intelligence in Improvised Theatre',
 'Exploration with Unreliable Intrinsic Reward  in Multi-Agent Reinforcement Learning',
 '1',
 'The Modeling and Quantification of Rhythmic to Non-rhythmic Phenomenon in Electrocardiography during Anesthesia',
 'Fake News Early Detection: A Theory-driven Model',
 'Autovocoder: Fast Waveform Generation from a Learned Speech Representation using Differentiable Digital Signal Processing',
 'Towards the D-Optimal Online Experiment Design for Recommender Selection',
 'Preference-driven Similarity Join',
 'Bandwidth-Optimal Random Shuffling for GPUs',
 'Relation Learning on Social Networks with Multi-Modal Graph Edge Variational Autoencoders',
 'Edge-Host Partitioning of Deep Neural Networks with Feature Space Encoding for Resource-Constrained Internet-of-Things Platforms',
 'HAPTIC SCIENCE AND TECHNOLOGY',
 'Proceedings Template - WORD',
 'IPI PAN slides',
 'The Multiscale Perturbation Method for Two-Phase Reservoir Flow Problems',
 'Fair lending needs explainable models for responsible recommendation',
 'POTs: The revolution will not be optimized?',
 'public helper_extended_130426.dvi',
 'Parallelizing Workload Execution in Embedded and High-Performance Heterogeneous Systems',
 'Paper Title (use style: paper title)',
 'Paper Title (use style: paper title)',
 'Cost-sensitive Learning of Deep Semantic Models for Sponsored Ad Retrieval',
 'Leveraging Historical Interaction Data for Improving Conversational Recommender System',
 'A Scalable Hybrid Research Paper Recommender System for Microsoft Academic',
 'Transaction / Regular Paper Title',
 'Sample manuscript showing specifications and style',
 'Elomaa01a.dvi',
 'Paper Title (use style: paper title)',
 'Learnability of the output distributions of local quantum circuits',
 'IET Submission Template',
 'Bayesian Inference with Generative Adversarial Network Priors',
 'Approximate Undirected Transshipment and Shortest Paths via Gradient Descent',
 'AN INVESTIGATION OF THE SEQUENTIAL SAMPLING METHOD',
 'Breaking the Softmax Bottleneck via Learnable Monotonic Pointwise Non-linearities',
 'A Comparative Analysis for Determining the Optimal Path using PSO and GA',
 'q.eps',
 'DeepTriangle: A Deep Learning Approach to Loss Reserving',
 'Well-behaved Online Load Balancing Against Strategic Jobs',
 '#Santiago is not #Chile, or is it? A Model to Normalize Social Media Impact',
 'Representation Learning with Fine-grained Patterns',
 'Lumos: A Library for Diagnosing Metric Regressions in Web-Scale Applications',
 'Energy-Aware Adaptive Offloading of Soft Real-Time Jobs in Mobile Edge Clouds',
 'Preparation of Papers in Two-Column Format for the Proceedings of the 2004 Sarnoff Symposium',
 'Evolutionary Echo State Network: evolving reservoirs in the Fourier space',
 '../article/zscore_edges_Pvalue.eps',
 'mean-field limit of interacting 2D nonlinear stochastic spiking neurons',
 'Your Title',
 'Multi-Output Artificial Neural Network for Storm Surge Prediction in North Carolina',
 'Splitting method for spatio-temporal search efforts planning',
 'Background',
 'Quantifying Uncertainties in Natural Language Processing Tasks',
 'Multi-Vehicle Mixed-Reality Reinforcement Learning for Autonomous Multi-Lane Driving',
 'Towards optimisation of openMP codes for synchronisation and data reuse',
 'Your Title Here',
 'How to combine three quantum states',
 'CLAD: A realistic Continual Learning benchmark for Autonomous Driving',
 'Frequency Bias in Neural Networks for Input of Non-Uniform Density',
 'Multi-instance Domain Adaptation for Vaccine Adverse Event Detection',
 'ENDT',
 '文章编号：',
 'Backprop with Approximate Activationsfor Memory-efficient Network Training',
 'LAMNER: Code Comment Generation Using Character Language Model and Named Entity Recognition',
 "ACMiner: Extraction and Analysis of Authorization Checks in Android's Middleware",
 'Java Based Distributed Learning Platform',
 'proj-year.eps',
 'STFU NOOB! Predicting Crowdsourced Decisions on Toxic Behavior in Online Games',
 'Paper Title (use style: paper title)',
 'Impact of Accuracy on Model Interpretations',
 'Format guide for AIRCC',
 'Off-Policy Actor-Critic',
 'Paper Title (use style: paper title)',
 'Using AI for Economic Upliftment of Handicraft Industry',
 'Removing biased data to improve fairness and accuracy',
 'HSICGP',
 'embc2012_3D Segmentation Method for OCT.docx',
 'Efficient Massively Parallel Join Optimization for Large Queries*',
 'Why Not to Use Binary Floating Point Datatypes in RDF',
 'On the Impact of Ground Sound',
 'Operation-Aware Soft Channel Pruning using Differentiable Masks',
 'Ranking for Relevance and Display Preferences in Complex Presentation Layouts',
 '4052',
 'Invariant Representations through Adversarial Forgetting',
 'A Survey on Software Defined Networking: Architecture for Next Generation Network',
 'Optimum Decoder for an Additive Video Watermarking with Laplacian Noise in H.264',
 'Image-based remapping of spatially-varying material appearance',
 'NFFT meets Krylov methods: Fast matrix-vector products for the graph Laplacian of fully connected networks',
 'T-GD: Transferable GAN-generated Images Detection Framework',
 'Deep Social Collaborative Filtering',
 'Mining (maximal) span-cores from temporal networks',
 'Exascale Deep Learning for Scientific Inverse Problems',
 'Multilevel Adaptive Sparse Leja Approximations',
 'A general sample complexity analysis of vanilla policy gradient',
 'General Graph Identification With Hashing',
 'Classification of Heterogeneous Operating-Column view',
 'Fluent: An AI Augmented Writing Tool for People who Stutter',
 'JAIR_final.dvi',
 'AZP: Automatic Specialization for Zero Values in Gaming Applications',
 'AMR Iso-Surface Extraction',
 'TriPoll: Computing Surveys of Triangles in Massive-Scale Temporal Graphs with Metadata',
 'Paper Title (use style: paper title)',
 'ES-WEB-WAP_ICISBC2013_-revision',
 'Spiking neural network for nonlinear regression',
 ' MoFlow: An Invertible Flow Model for Generating Molecular Graphs',
 'Learning to Steer by Mimicking Features from Heterogeneous Auxiliary Networks',
 'MIRA:Leveraging Multi-Intention Co-click Information in Web-scale Document Retrieval using Deep Neural Networks',
 'Author(s)',
 'Aegis: A Context-aware Security Framework for Smart Home Systems',
 'Computing Research Challenges in Next Generation Wireless',
 'DOI: 10',
 'Governing autonomous vehicles: emerging responses for safety, liability, privacy, cybersecurity, and industry risks',
 'Adaptive and Azimuth-Aware Fusion Network of Multimodal Local Features for 3D Object Detection',
 'Parameterized Algorithms for Matrix Completion With Radius Constraints',
 'Exploration in Online Advertising Systems with Deep Uncertainty-Aware Learning',
 'Constrained Type Families (extended version)',
 'Deep Reinforcement Learning for Optimal Stopping with Application in Financial Engineering',
 'Impact of Gender and Age on performing Complex Search Tasks Online',
 'Attentive Recurrent Comparators',
 'Classical and quantum dynamic programming for Subset-Sum and variants',
 'Scalable Deep Generative Modeling for Sparse Graphs',
 'Tight Lower Bound for Average Number of Terms in Optimal Double-base Number System',
 'An Intelligent Non-Invasive Real Time Human Activity Recognition System for Next-Generation Healthcare',
 'Generalized eigen, singular value, and partial least squares decompositions: The GSVD package',
 'decay50.eps',
 'Overleaf Example',
 "Measuring the meaning of words in contexts: An automated analysis of controversies about 'Monarch butterflies,' 'Frankenfoods,' and 'stem cells'",
 'FinRL: Deep Reinforcement Learning Framework to Automate Trading in Quantitative Finance',
 'Was wird durch den h index und seine Derivate (wie den g index und den R index) tatsächlich gemessen',
 'Multi-Agent Pathfinding: Definitions, Variants, and Benchmarks',
 'Networked Intelligence',
 'Are Multi-language Design Smells Prevalent? An Empirical Study',
 'An IoT-Based Framework for Remote Fall Monitoring',
 'Paper Title (use style: paper title)',
 'PoW, PoS, & Hybrid protocols: A Matter of Complexity?',
 'Understanding the Stability of Deep Control Policies for Biped Locomotion',
 'ICCSC 2004',
 'SpaceTEE: Secure and Tamper-Proof Computing in Space using CubeSats',
 'Towards Understanding the Adversarial Vulnerability of Skeleton-based Action Recognition',
 'Hybrid CNN Based Attention with Category Prior for User Image Behavior Modeling',
 'An Empirical Comparison of the Summarization Power of Graph Clustering Methods',
 '2020_VIS_Popchart-9.pdf',
 'On the Relation between Quality-Diversity Evaluation and Distribution-Fitting Goal in Text Generation',
 'A Termination Criterion for Probabilistic Point Clouds Registration',
 'Format guide for AIRCC',
 'An Online-Learning Approach to Inverse Optimization',
 'Learning sparse representations in reinforcement learning',
 'Paper Title (use style: paper title)',
 'AI-based artistic representation of emotions from EEG signals: a discussion on fairness, inclusion, and aesthetics',
 'RAILD: Towards Leveraging Relation Features for Inductive Link Prediction In Knowledge Graphs',
 'lande-arx-hyper',
 'Paper Title (use style: paper title)',
 'What We Can Learn From Visual Artists About Software Development',
 'PREPARATION OF THE CAMERA-READY AND ELECTRONIC VERSIONS OF YOUR PAPER FOR THE PROCEEDINGS OF THE 2001 AMOS TECHNICAL CONFERENCE',
 'Role of Attentive History Selection in Conversational Information Seeking',
 'Scale Steerable Filters for Locally Scale-Invariant Convolutional Neural Networks',
 'Graph Neural Network Based VC Investment Success Prediction',
 'Doubly Robust Off-policy Evaluation for Reinforcement Learning',
 'Title',
 'Gaussian Processes to speed up MCMC with automatic exploratory-exploitation effect',
 'On the Exactness of an Energy-efficient Train Control model based on Convex Optimization',
 'Ranking Archived Documents for Structured Queries on Semantic Layers',
 'EdgeLens',
 'What are Weak Links in the npm Supply Chain?',
 'str_sigkdd2020 Approved for public release',
 'AAAI Press Formatting Instructions for Authors Using LaTeX -- A Guide',
 'Differentially Private Densest Subgraph Detection',
 'To Interpolate or not to Interpolate:  PRF, Dense and Sparse Retrievers',
 'Towards Immersive Virtual Reality Simulations of Bionic Vision',
 'Model-free Policy Learning with Reward Gradients',
 'ToriLLE: Learning Environment for Hand-to-Hand Combat',
 'Meetings and Mood – Related or Not?Insights from Student Software Projects',
 'Conjunctive queries with self-joins, towards a fine-grained complexity analysis',
 'Parity-Checked Strassen Algorithm ',
 'DeepOPF: Deep Neural Network for DC Optimal Power Flow',
 'Constrained Bilinear Factorization Multi-view Subspace Clustering',
 'Amortised Resource Analysis with Separation Logic',
 'Modeling, Control, and Decision Support in Complex Systems',
 'AI Tax: The Hidden Cost of AI Data Center Applications',
 'ISME2020 - Paper Formatting and Preparation',
 'Discover the Hidden Attack Path in Multi-domain Cyberspace  Based on Reinforcement Learning',
 'VapeTracker: Tracking Vapor Consumption to Help E-cigarette Users Quit',
 'T',
 'TDGIA: Effective Injection Attacks on Graph Neural Networks',
 'A Qualitative Post-Experience Method for Evaluating Changes in VR Presence Experience Over Time',
 'Visually Explainable Recommendation',
 'adapt.response.plot.var.eps',
 'Valuing knowledge, information and agency in Multi-agent Reinforcement Learning: a case study in smart buildings',
 'Compiler-Driven FPGA Virtualization with SYNERGY',
 'Expectation of the Largest Betting Size in Labouchère System',
 'CPP_part2.pdf',
 'Competition between simultaneous demand-side flexibility options: The case of community electricity storage systems',
 'Lecture Notes in Computer Science:',
 'Clustered Sampling: Low-Variance and Improved Representativity for Clients Selection in Federated Learning',
 'Ontology drift is a challenge for explainable data governance',
 'Beyond Textual Issues: Understanding the Usage and Impact of GitHub Reactions',
 'ModelingToolkit',
 'Computational linguistic assessment of textbook and online learning media by means of threshold concepts in business education',
 'Preparation of Papers in Two-Column Format',
 'Tensorized Embedding Layers for Efficient Model Compression',
 'Deciding twin-width at most 4 is NP-complete',
 'Machine Vision: A Data Acquisition System',
 'Volumetric Isosurface Rendering with Deep Learning-Based Super-Resolution',
 'Proceedings of',
 ' ',
 'Schematic Memory Persistence and Transience for Efficient and Robust Continual Learning',
 'Generalized Points-to Graphs: A New Abstraction of Memory in the Presence of Pointers',
 'Memory-Optimality for Non-Blocking Containers',
 'Insert Your Title Here',
 'Measuring News Similarity Across Ten U.S. News Sites',
 'The Connection between Process Complexity of Event Sequences and Models discovered by Process Mining',
 'Semi-Supervised Speech Recognition via Local Prior Matching',
 'A Quantitative Comparison between Shannon and Tsallis–Havrda–Charvat Entropies Applied to Cancer Outcome Prediction',
 'differentiate_T500cut_loglog.eps',
 'Granular Generalized Variable Precision Rough Sets and Rational Approximations',
 'Single Shot Temporal Action Detection',
 'Linear Programming using Limited-Precision Oracles',
 'Sequential Optimization Numbers and Conjecture about Edge-Symmetry and Weight-Symmetry Shortest Weight-Constrained Path',
 'Characterization of canonical systems with six types of coins  for the change-making problem',
 'High-Dimensional Similarity Search with Quantum-Assisted Variational Autoencoder',
 'Exploiting Temporal Coherence for Multi-modal Video Categorization',
 'Identifying Sources and Sinks in the Presence of Multiple Agents with Gaussian Process Vector Calculus',
 'Combinations of Qualitative Winning for  Stochastic Parity Games',
 'FreshDiskANN: A Fast and Accurate Graph-Based ANN Index for Streaming Similarity Search',
 'ULN_aaai19',
 'Successive Pruning for Model Compression via Rate Distortion Theory',
 'graziotin_fagerholm',
 'Proceedings Template - WORD',
 'Sparse and Imperceptible Adversarial Attack via a Homotopy Algorithm',
 'Title',
 'IJCA_Revised_Current_Version_March_2010',
 'Article',
 'Safe-visor Architecture for Sandboxing (AI-based) Unverified Controllers in Stochastic Cyber-Physical Systems',
 'A machine learning model for identifying cyclic alternating patterns in the sleeping brain',
 'Cognition in Software Engineering: A Taxonomy and Survey of a Half-Century of Research',
 'MicroNets: Neural Network Architectures for Deploying TinyML Applications on Commodity Microcontrollers',
 'Detecting Anomalies in Sequential Data with Higher-order Networks',
 'Efficient Specialized Spreadsheet Parsing for Data Science',
 'Classification of Web Phishing Kits for early detection by platform providers',
 'Scratch Community Blocks: Supporting Children as Data Scientists',
 'An Evolutionary Framework for Automatic and Guided Discovery of Algorithms ',
 'lang03a.dvi',
 'Cost-effective Interactive Attention Learning with Neural Attention Process',
 'Paper Title (use style: paper title)',
 'Random matrix-improved estimation of covariance matrix distances',
 'Local Search for Policy Iteration in Continuous Control',
 'Graph Embedding via Diffusion-Wavelets-Based Node Feature Distribution Characterization',
 'The Past and Present of Imitation Learning',
 'Beta10Rho99.eps',
 'Attributed Graph Modeling with Vertex Replacement Grammars',
 'Your Title',
 'HyperProv: Decentralized Resilient Data Provenance at the Edge with Blockchains',
 'Applying physics-based loss functions to neural networks for improved generalizability in mechanics problems',
 'Using Integrated Gradients to explain Linguistic Acceptability learnt by BERT',
 'Semi-Supervised Visual Representation Learning for Fashion Compatibility',
 'Language-agnostic Topic Classification for Wikipedia',
 'MSO Queries on Trees: Enumerating Answers under Updates Using Forest Algebras',
 'An Empirical Study of Path Feasibility Queries',
 'Automatic Product Ontology Extraction from Textual Reviews',
 'Paper Title (use style: paper title)',
 'Knowledge-Based Automatic Generation of Linear Algebra Algorithms and Code',
 'Invariant Causal Prediction for Block MDPs',
 'Universally typical Sets for ergodic Sources of multidimensional Data',
 '(divide_conquer.pdf)',
 'An Efficient Analyses of the Behavior of One Dimensional Chaotic Maps using 0-1 Test and Three State Test',
 'Not All Ops Are Created Equal!',
 'Colbert_etal_CyberPhysicalWargaming_arxiv0',
 'Article',
 'On the Implicit Bias of Dropout',
 'Transaction / Regular Paper Title',
 'report',
 'Deep Learning methods for automatic evaluation of delayed enhancement-MRI. The results of the EMIDEC challenge.',
 'REFUGE Challenge: A Unified Framework for Evaluating Automated Methods for Glaucoma Assessment from Fundus Photographs',
 'Traceability Support for Multi-Lingual Software Projects',
 'Paper Title (use style: paper title)',
 'Network-Aware Strategies in Financial Systems',
 'Handheld Multi-Frame Super-Resolution',
 'paper.dvi',
 'Meta-Learned Invariant Risk Minimization',
 'A template for the arxiv style',
 'WDC Products: A Multi-Dimensional Entity Matching Benchmark',
 'Task-Aware Compressed Sensing with Generative Adversarial Networks',
 'Discount Factor as a Regularizer in Reinforcement Learning',
 'Paper Title (use style: paper title)',
 'Deterministic Combinatorial Replacement Paths and Distance Sensitivity Oracles',
 'Learning from History and Present: Next-item Recommendation via Discriminatively Exploiting User Behaviors',
 'Scheduling for Optimal Rate Allocation in Ad Hoc Networks Subject to Heterogeneous Delay Constraints',
 'An OAI-PMH-based Web Service for the Generation of Co-Author Networks',
 'A Cost- Effective Design of Reversible Programmable Logic Array',
 'A Deep Learning Approach to Mapping Irrigation: IrrMapper-U-Net',
 'A Data Driven Method of Feedforward Compensator Optimization for Autonomous Vehicle Control',
 'Formally Secure Compilation of Unsafe Low-Level Components',
 'Hiding in the Particles: When Return-OrientedProgramming Meets Program Obfuscation',
 'for CCE.docx',
 'attribute-gen.eps',
 'Extended Abstract Template',
 'hep-th',
 'Estimating Active Cases of COVID-19',
 'The Strength of Connectivity of Random Graphs induced by Pairwise Key Predistribution Schemes: Implications on Security and Reliability of Heterogeneous Sensor Networks',
 'Datacenter RPCs can be General and Fast',
 'Sparse evolutionary Deep Learning with over one million artificial neurons on commodity hardware',
 'Automatic Semantic Style Transfer using Deep Convolutional Neural Networks and Soft Masks',
 'Hierarchical growing grid networks for skeleton based action recognition',
 'Reinforcement Learning Agent Training with Goals for Real World Tasks',
 'A Robust Interactive Facial Animation Editing System',
 'Avoiding and Escaping Depressions in Real-Time Heuristic Search',
 'Unsupervised Learning of Sensorimotor Affordances by Stochastic Future Prediction',
 'Efficient Algorithms for Battleship',
 'PLOTS: Procedure Learning from Observations using Subtask Structure',
 'Reflective Diary for Professional Development of Novice Teachers',
 'RPD',
 'Adversarial Attacks and Detection on Reinforcement Learning-Based Interactive Recommender Systems',
 'Sample manuscript showing style and formatting specifications for SPIE e-journal papers',
 'POI Semantic Model with a Deep Convolutional Structure',
 'Discovering Interesting Cycles in Directed Graphs',
 'Distributed Kalman filtering with minimum-time consensus algorithm',
 'A recursive system-free single-step temporal discretization method for finite difference methods',
 'Computational Complexity of Covering Two-vertex Multigraphs with Semi-edges',
 'New Complexity Results on Coalitional Manipulation of Borda',
 'Impartial selection with prior information',
 'Date of publication xxxx 00, 0000, date of current version xxxx 00, 0000',
 'Agglomeration-Based Geometric Multigrid Solvers for Compact Discontinuous Galerkin Discretizations on Unstructured Meshes',
 'BIOSTEC_2020',
 'Productivity of Non-Orthogonal Term Rewrite Systems',
 'Leveraging Catalog Knowledge Graphs for Query Attribute Identification in E-Commerce Sites',
 'On Image Classification: Correlation v.s. Causality',
 'Learning to Ask: Question-based Sequential Bayesian Product Search',
 'Kdhry.eps',
 'Coreset-based Strategies for Robust Center-type Problems']
				var txt = document.getElementById("paper_name").value;
				txt_lst = txt.split(" ");
				
				for(let k = 0; k<txt_lst.length;k++){
					
				
					for(let i=0;i<lst.length;i++){
						x = lst[i].split(" ");
						for(let j= 0;j<x.length;j++){
							if(txt_lst[k]==x[j]){
								
								val = lst[i];
								final_list.push(val);
								
							}
						}
				
					}
				}
					if(final_list.length>0){
						alert(final_list);
					}
					else{
						alert("No recommendations");
					}
					document.getElementById("paper_name").value =  " ";
					
				}
				